# Generated by Django 4.1 on 2022-11-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='message',
            field=models.TextField(max_length=2000),
        ),
    ]
